//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.TASKS = new HashSet<TASK>();
        }
    
        public short ID_USER { get; set; }
        public string NAME { get; set; }
        public string LASTNAME { get; set; }
        public string ROLE { get; set; }
    
        public virtual ICollection<TASK> TASKS { get; set; }
    }
}
